#pragma once

#include <string>

enum class BLOCK_TYPE{
	AIR,
	WALL,
	BUTTON,
	ERROR
};

enum class BUTTON_TYPE{
	NOTHING,
	ESCAPE_RESUME,
	ESCAPE_RESTART,
	ESCAPE_SETTINGS,
	ESCAPE_MAIN_MENU,
	ESCAPE_PAUSED,
	SETTINGS_EDITOR_TOGGLE,
	SETTINGS_BLablala,
	EDITOR_ENTITY_TOGGLE,
	EDITOR_BLOCK_SELECT,
	EDITOR_WALL,
	EDITOR_INDEX_SHOW,
	EDITOR_INDEX_INCREASE,
	EDITOR_INDEX_DECREASE,
	EDITOR_BLOCK_SHOW,
	EDITOR_INFO,
	EDITOR_SPECIAL_MOVEMENT_ON_BUTTON,
	EDITOR_SPECIAL_PAUSE_BUTTON,
	EDITOR_ENTITY_IS_SELECTED_TEXT,
	EDITOR_PLAIN_TEXT,
	EDITOR_SELECTED_ENTITY_NUMBER,
};

enum class GAME_STATE{
	PLAYING,
	ESCAPE,
	SETTINGS,
	MAIN_MENU
};

enum class CMAERA_TYPE{
	BOTH,
	PLAYER1,
	PLAYER2
};


BLOCK_TYPE STRING_TO_BLOCK_TYPE(std::string the_string);

std::string BLOCK_TYPE_TO_STRING(BLOCK_TYPE& type);